### ISSUE TITLE
estimated time remaining increments upwards instead of downwards

### ISSUE THREAD

**Issue by eponymous301** [eluv-io/elv-studio#19]
noticed on prod

**Comment by eponymous301** [comment]
Possibly a bug in elv-lro-status - checking...

**Comment by eponymous301** [comment]
Bugfix committed to @eluv-io/elv-lro-status and npm package updated to v3.0.6

https://github.com/eluv-io/elv-lro-status/commit/7744efe1530e4bd2c2f3b927dd2bbfa56096fe91

**Comment by elv-zenia** [comment]
Updated elv-lro-status to 3.0.6 in elv-studio
https://github.com/eluv-io/elv-studio/commit/7b9b2c64d2338bd100dbcffff5a673279f586dbb

**Comment by eponymous301** [comment]
Value now moves in the right direction after bug fix to eluv-io/elv-lro-status - one more change still needed though - ETA message update needs to stop once an error condition is detected - the automatic compensation for time elapsed between API calls is resulting in ETA display still decrementing while error is displayed.

**Comment by elv-zenia** [comment]
Last issue-ETA messaging continues updating after error detection--verified by @elv-gerald: https://eluvio.slack.com/archives/CF7AQGUH0/p1678936577240229?thread_ts=1678930558.671769&cid=CF7AQGUH0 (5th bullet point)
