### ISSUE TITLE
Library with DRM cert and No Profile fails to ingest DRM mez

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-studio#29]
I was testing the following case 

> If the library has NO profile and HAS DRM cert, set the profile as a default DRM profile

I set up a library to only have the fps cert with no profile. While testing I was only able to ingest `clear` mezzanines into that library. Any ingest with drm resulted in the following error
```
{
  "ok": false,
  "errors": [
    "ABR Profile has no non-clear playout_formats"
  ]
}
```

**Comment by elv-zenia** [comment]
Fixed by https://github.com/eluv-io/elv-studio/pull/26/files/10b077ae7377ab1debb812490dc451acdb21e5b4..c69984a95c11e0a76eba242d45c25f60fced783a. Deployed to demo.

**Comment by elv-gerald** [comment]
Verified. I tested all the profile on a library that only has a DRM cert. Everything ingested and had the correct playout formats.
