### ISSUE TITLE
Encrypt Master files and use unencrypted option for Clear ingests

### ISSUE THREAD

**Issue by elv-zenia** [eluv-io/elv-studio#31]
- Always encrypt Master parts on upload
- If clear encryption is chosen, Mezzanine parts should not be encrypted (set the option in the ABR profile to store_clear: true)

**Comment by elv-zenia** [comment]
Fixed by [c1e0633](https://github.com/eluv-io/elv-studio/commit/c1e0633c381c8184ba758d79e46e401a937d18da). Deployed to demo.

**Comment by elv-gerald** [comment]
Verified. 

I tested and verified the following cases

clear lib
  - mez is clear 
  - master is encrypted
  - tested on same and diff objects 

drm enabled lib
  clear
    - mez is clear 
    - master is encrypted
    - tested on same and diff objects

  drm 
    - mez is not clear
    - master is encrypted
    - tested on same and diff objects
    
    
 I verified by ensuring the mezzanine has the correct `store_clear` value depending on the case and that the master was encrypted using the file browser.
