### ISSUE TITLE
Ingest fails at setting localStorage when a non-ASCII character is present

### ISSUE THREAD

**Issue by elv-zenia** [eluv-io/elv-studio#32]
The ingest fails after creation when either a form field or a file name has a non-ASCII character.

Example use case from Sam: `I tried uploading my file FARAÓ_CORUJA_MIX.wav twice and it crashed the app both times after submitting, the third time I substituted in an O and it worked.`

Console errors: 
- RangeError: Maximum call stack size exceeded.
- Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

https://eluvio.slack.com/archives/CF7AQGUH0/p1679850828704099?thread_ts=1679698463.014159&cid=CF7AQGUH0

**Comment by elv-zenia** [comment]
This changes encoding/decoding of localStorage data in three areas:
- Decoding when app is first loaded
- Encoding during event fired when clicking Clear Inactive Jobs
- Encoding during a new ingest
Deployed to demo. @elv-gerald Ready for verification.

**Comment by elv-gerald** [comment]
This change looks good. I test the following scenarios

- filename and descriptions have a non-ascii character
- only filename has a non-ascii character
- only descriptions have a non ascii-character
- filename and descriptions ONLY have a ascii characters

I tested the above with aws and file based ingests

**Comment by elv-zenia** [comment]
@elv-gerald From the code review, I changed the encoding/decoding to use utilities built into client-js. Sorry, could you run through those scenarios again?

**Comment by elv-gerald** [comment]
I re-rean the same set of test and the everything passed with no failures. Change are good.

**Comment by elv-zenia** [comment]
Deployed to prod.
